ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Models/PerformanceTest.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PerformanceTestGraph.Models
{
    [Table("aom.PerfomanceTests")]
    public class PerformanceTest
    {
        [Column(Order = 0)]
        [Key]
        [StringLength(45)]
        public string AssemblyVersion { get; set; }

        [Column(Order = 1)]
        [Key]
        public DateTime DateCreated { get; set; }
        
        [StringLength(45)]
        public string PageName { get; set; }

        [Column]
        public decimal ElapsedTime { get; set; }
    }
}

ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Models/PerformanceTestGrouping.cs
using System;

namespace PerformanceTestGraph.Models
{
    public class PerformanceTestGrouping
    {
        public string AssemblyVersion { get; set; }
        
        //public DateTime DateCreated { get; set; }
        
        public string PageName { get; set; }
        
        public decimal ElapsedTime { get; set; }
    }
}

ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Models/PerformanceTestModel.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;

namespace PerformanceTestGraph.Models
{
    public class PerformanceTestModel : DbContext
    {
        public PerformanceTestModel() : base("aomconnection") { }

        public virtual IDbSet<PerformanceTest> PerformanceTests { get; set; }

        public List<PerformanceTestGrouping> GetAveragePerformanceTestResultsforVersion()
        {
            return (from pt in this.PerformanceTests
                    group pt by new { pt.AssemblyVersion, pt.PageName } into grp
                    select new PerformanceTestGrouping()
                    {
                        AssemblyVersion = grp.FirstOrDefault().AssemblyVersion,
                        //DateCreated = grp.Max(x => x.DateCreated),
                        PageName = grp.FirstOrDefault().PageName,
                        ElapsedTime = grp.Select(x => x.ElapsedTime).Average()
                    })
                .ToList() // LINQ to Entities cannot translate int.parse(), so we put results in memory first
                .OrderBy(x => int.Parse(x.AssemblyVersion.Replace(".", ""))).ThenBy(x => x.PageName)
                .ToList();
        }

    }
}

ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Controllers/tst_PerformanceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using PerformanceTestGraph.Models;
using PerformanceTestGraph.ViewModel;

namespace GoogleCharts.Controllers
{
    public class tst_PerformanceController : Controller
    {
        // GET: tst_Performance
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Index()
        {
            using (var db = new PerformanceTestModel())
            {
                var performanceTestResultGroupings = db.GetAveragePerformanceTestResultsforVersion();

                var result = new DynamicGraphData
                {
                    DynamicColumnLabels = performanceTestResultGroupings.Select(pr => pr.PageName).Distinct().OrderBy(pr => pr).ToArray(),
                    ColumnValues = new List<PageNameGroupByVm>()
                };

                foreach (var distinctAssembly in performanceTestResultGroupings.Select(pr => pr.AssemblyVersion).Distinct())
                {
                    var group = new PageNameGroupByVm()
                    {
                        AssemblyVersion = distinctAssembly,
                        Pages = new double?[result.DynamicColumnLabels.Length],
                    };

                    for (var i = 0; i < result.DynamicColumnLabels.Length; i++)
                    {
                        group.Pages[i] = performanceTestResultGroupings.Where(pr => pr.AssemblyVersion == distinctAssembly && pr.PageName == result.DynamicColumnLabels[i])
                            .Select(pr => (double?)Convert.ToDouble(pr.ElapsedTime))
                            .SingleOrDefault();
                    }
                    result.ColumnValues.Add(group);
                }
                return View(result);
            }
        }
    }
}

ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Views/Home/About.cshtml
@*@{
        ViewBag.Title = "About";
    }
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>*@

ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Views/Home/Contact.cshtml
@*@{
        ViewBag.Title = "Contact";
    }
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>*@

ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Views/Home/Index.cshtml
@*@{
        ViewBag.Title = "Home Page";
    }

    <div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>
    <div>
        @Html.ActionLink("Performance", "Index", "tst_Performance")<br />
    </div>
    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@

ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@

ArgusOpenMarkets-lpgfrontend/AOM/PerformanceTestGraph/Views/tst_Performance/Index.cshtml
@model PerformanceTestGraph.ViewModel.DynamicGraphData

@{
    ViewBag.Title = "Test Performance Graph";
}

<div id="chart_div" style="width: 2000px; height: 1000px;">
    <h1>Single User Performance Graphs</h1>
</div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
@*<script type="text/javascript" src="~/Scripts/underscore.js"></script>*@
<script type="text/javascript">

    var result = @Html.Raw(Json.Encode(Model));

     google.load("visualization", "1.1", { packages: ["corechart"] });
    //google.charts.load('current', {'packages':['line']});

    google.setOnLoadCallback(drawChart);

    function drawChart() {

       // Create and populate the data table.
        var data = new google.visualization.DataTable();

        data.addColumn('string', 'AssemblyVersion');
        for (var i = 0; i < result.DynamicColumnLabels.length; i++) {
            data.addColumn('number', result.DynamicColumnLabels[i]);
        }

        for (var j = 0; j < result.ColumnValues.length; j++) {
            data.addRow([result.ColumnValues[j].AssemblyVersion, ...result.ColumnValues[j].Pages]);
        }
        var options = {
            title: 'Performance of Pages',
            //curveType: 'function',

            explorer: {
                actions: ['dragToZoom', 'rightClickToReset'],
              //  axis: 'horizontal'
                maxZoomIn : 0.01

            },
            hAxis: {
                title: 'Builds' , slantedText: true, slantedTextAngle: 270
            },

            pointSize: 5,

            vAxis: {
                title: 'Time taken in seconds',
            minValue: 0

            //},

            //animation: {
            //    duration: 1000,
            //    easing: 'in',
            //    startup: true
            }
            //interpolateNulls: true
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

       // var chart = new google.charts.Line(document.getElementById('chart_div'));

         //chart.draw(data, google.charts.Line.convertOptions(options));
         drawGoogleChart();

        function drawGoogleChart() {

            chart.draw(data, options);
        }

    }
</script>